
CREATE TABLE bnb_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT,
    email TEXT NOT NULL,
    password VARCHAR(72) NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);
